### PR TITLE
Fix cross entropy.

### LINKED ISSUE #46: Fix cross entropy.

### PR DESCRIPTION
**Pull request by gpestre**
Fixes #46. Verified against two-class example (binary cross-entropy); should also work for multi-class cross-entropy but not tested yet.

### CODE REVIEW

File: src/test_losses.cpp [hunk 1]
```diff
@@ -40,16 +40,24 @@ int main(){
...
-    std::cout << "Binary cross-entropy ( -(log(4/7)+log(1-3/7)) ): " + std::to_string(loss_entropy) << std::endl;
+    double loss_entropy = LossFunction("cross_entropy").calculate(labels);
+    std::cout << "Binary cross-entropy ( -( 4/7*log2(4/7) + 3/7*log2(3/7) ) ): " + std::to_string(loss_entropy) << std::endl;
+    std::cout << std::endl;
+    
+    std::cout << "Calculate loss (test 2)." << std::endl;
+    DataVector labels2 = DataVector({1,1,1,1,1,2,2,2,2,2,2,2,2});
+    std::cout << labels2 << "Counts : " << LabelCounter(labels2) << std::endl;
+    double loss_entropy2 = LossFunction("cross_entropy").calculate(labels2);  // count(1)=5, count(2)=8.
+    std::cout << "Binary cross-entropy ( -( 5/13*log2(5/13) + 8/13*log2(8/13) ) ): " + std::to_string(loss_entropy2) << std::endl;
```
Comment (johannes-kk) [inline src/test_losses.cpp:59]: Assuming this is consistent with the result of running the function on our contrived dataset, then it looks good to me 👍

**Review by johannes-kk — APPROVED** [review]
LGTM, assuming the tests yield the correct result on our contrived dataset – which, as far as I can see, it should 🙂
